version: '3'

services:
  m3u8-recorder:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: m3u8-recorder
    ports:
      - "3838:3838"
    volumes:
      - /path/to/downloads:/app/downloads
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      - DOWNLOADS_DIR=/app/downloads